name: Deploy
on:
  push:
    branches: [master]
  schedule:
    - cron: "* * * 1,2,3,4,5,6,7,8,9,10,11,12 *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.HOME_PID }}
          ALIAS_DOMAINS: ${{ secrets.HOME_ALIAS_DOMAINS }}
          GITHUB_DEPLOYMENT: true
